export const GAMBLERS_2024 = [
  {
    name: "Elin",
    bets: [
      { matchType: "group", winner: "Hector Apelgren & Peter Apelgren" },
      { matchType: "group", winner: "Ebba Kleberg von Sydow & Anders Tegnell" },
      { matchType: "group", winner: "Hanna Dorsin & Emma Molin" },
      { matchType: "group", winner: "Ebba Kleberg von Sydow & Anders Tegnell" },
      { matchType: "group", winner: "Hector Apelgren & Peter Apelgren" },
      { matchType: "group", winner: "Hector Apelgren & Peter Apelgren" },
      { matchType: "group", winner: "Farah Abadi & Johan Glans" },
      { matchType: "group", winner: "Farah Abadi & Johan Glans" },
      { matchType: "group", winner: "Jennifer Kücükaslan & Johan Kücükaslan" },
      { matchType: "group", winner: "Messiah Hallberg & Sara Wimmercranz" },
      { matchType: "group", winner: "Jennifer Kücükaslan & Johan Kücükaslan" },
      { matchType: "group", winner: "Farah Abadi & Johan Glans" },
      {
        matchType: "semifinal",
        semifinalFirst: "Hector Apelgren & Peter Apelgren",
        semifinalSecond: "Farah Abadi & Johan Glans",
      },
      { matchType: "final", winner: "Hector Apelgren & Peter Apelgren" },
    ],
  },
  {
    name: "Fabian",
    bets: [
      { matchType: "group", winner: "Hector Apelgren & Peter Apelgren" },
      { matchType: "group", winner: "Hanna Dorsin & Emma Molin" },
      { matchType: "group", winner: "Gry Forssell & Jonas Rhodiner" },
      { matchType: "group", winner: "Gry Forssell & Jonas Rhodiner" },
      { matchType: "group", winner: "Hector Apelgren & Peter Apelgren" },
      { matchType: "group", winner: "Hector Apelgren & Peter Apelgren" },
      { matchType: "group", winner: "Anders Eldeman & Christoffer Nyqvist" },
      { matchType: "group", winner: "Jennifer Kücükaslan & Johan Kücükaslan" },
      { matchType: "group", winner: "Messiah Hallberg & Sara Wimmercranz" },
      { matchType: "group", winner: "Messiah Hallberg & Sara Wimmercranz" },
      { matchType: "group", winner: "Jennifer Kücükaslan & Johan Kücükaslan" },
      { matchType: "group", winner: "Messiah Hallberg & Sara Wimmercranz" },
      {
        matchType: "semifinal",
        semifinalFirst: "Hector Apelgren & Peter Apelgren",
        semifinalSecond: "Hanna Dorsin & Emma Molin",
      },
      { matchType: "final", winner: "Hector Apelgren & Peter Apelgren" },
    ],
  },
  {
    name: "Fanni",
    bets: [
      { matchType: "group", winner: "Hector Apelgren & Peter Apelgren" },
      { matchType: "group", winner: "Ebba Kleberg von Sydow & Anders Tegnell" },
      { matchType: "group", winner: "Hanna Dorsin & Emma Molin" },
      { matchType: "group", winner: "Ebba Kleberg von Sydow & Anders Tegnell" },
      { matchType: "group", winner: "Hector Apelgren & Peter Apelgren" },
      { matchType: "group", winner: "Hector Apelgren & Peter Apelgren" },
      { matchType: "group", winner: "Farah Abadi & Johan Glans" },
      { matchType: "group", winner: "Farah Abadi & Johan Glans" },
      { matchType: "group", winner: "Messiah Hallberg & Sara Wimmercranz" },
      { matchType: "group", winner: "Anders Eldeman & Christoffer Nyqvist" },
      { matchType: "group", winner: "Anders Eldeman & Christoffer Nyqvist" },
      { matchType: "group", winner: "Farah Abadi & Johan Glans" },
      {
        matchType: "semifinal",
        semifinalFirst: "Hector Apelgren & Peter Apelgren",
        semifinalSecond: "Ebba Kleberg von Sydow & Anders Tegnell",
      },
      { matchType: "final", winner: "Hector Apelgren & Peter Apelgren" },
    ],
  },
  {
    name: "Gustav",
    bets: [
      { matchType: "group", winner: "Hector Apelgren & Peter Apelgren" },
      { matchType: "group", winner: "Ebba Kleberg von Sydow & Anders Tegnell" },
      { matchType: "group", winner: "Gry Forssell & Jonas Rhodiner" },
      { matchType: "group", winner: "Ebba Kleberg von Sydow & Anders Tegnell" },
      { matchType: "group", winner: "Hector Apelgren & Peter Apelgren" },
      { matchType: "group", winner: "Hector Apelgren & Peter Apelgren" },
      { matchType: "group", winner: "Anders Eldeman & Christoffer Nyqvist" },
      { matchType: "group", winner: "Farah Abadi & Johan Glans" },
      { matchType: "group", winner: "Messiah Hallberg & Sara Wimmercranz" },
      { matchType: "group", winner: "Messiah Hallberg & Sara Wimmercranz" },
      { matchType: "group", winner: "Anders Eldeman & Christoffer Nyqvist" },
      { matchType: "group", winner: "Messiah Hallberg & Sara Wimmercranz" },
      {
        matchType: "semifinal",
        semifinalFirst: "Hector Apelgren & Peter Apelgren",
        semifinalSecond: "Ebba Kleberg von Sydow & Anders Tegnell",
      },
      { matchType: "final", winner: "Hector Apelgren & Peter Apelgren" },
    ],
  },
  {
    name: "Irma",
    bets: [
      { matchType: "group", winner: "Hector Apelgren & Peter Apelgren" },
      { matchType: "group", winner: "Hanna Dorsin & Emma Molin" },
      { matchType: "group", winner: "Hanna Dorsin & Emma Molin" },
      { matchType: "group", winner: "Ebba Kleberg von Sydow & Anders Tegnell" },
      { matchType: "group", winner: "Hector Apelgren & Peter Apelgren" },
      { matchType: "group", winner: "Hector Apelgren & Peter Apelgren" },
      { matchType: "group", winner: "Farah Abadi & Johan Glans" },
      { matchType: "group", winner: "Farah Abadi & Johan Glans" },
      { matchType: "group", winner: "Jennifer Kücükaslan & Johan Kücükaslan" },
      { matchType: "group", winner: "Anders Eldeman & Christoffer Nyqvist" },
      { matchType: "group", winner: "Jennifer Kücükaslan & Johan Kücükaslan" },
      { matchType: "group", winner: "Farah Abadi & Johan Glans" },
      {
        matchType: "semifinal",
        semifinalFirst: "Hector Apelgren & Peter Apelgren",
        semifinalSecond: "Farah Abadi & Johan Glans",
      },
      { matchType: "final", winner: "Hector Apelgren & Peter Apelgren" },
    ],
  },
  {
    name: "Markus",
    bets: [
      { matchType: "group", winner: "Ebba Kleberg von Sydow & Anders Tegnell" },
      { matchType: "group", winner: "Ebba Kleberg von Sydow & Anders Tegnell" },
      { matchType: "group", winner: "Hanna Dorsin & Emma Molin" },
      { matchType: "group", winner: "Ebba Kleberg von Sydow & Anders Tegnell" },
      { matchType: "group", winner: "Hector Apelgren & Peter Apelgren" },
      { matchType: "group", winner: "Hector Apelgren & Peter Apelgren" },
      { matchType: "group", winner: "Anders Eldeman & Christoffer Nyqvist" },
      { matchType: "group", winner: "Jennifer Kücükaslan & Johan Kücükaslan" },
      { matchType: "group", winner: "Jennifer Kücükaslan & Johan Kücükaslan" },
      { matchType: "group", winner: "Anders Eldeman & Christoffer Nyqvist" },
      { matchType: "group", winner: "Jennifer Kücükaslan & Johan Kücükaslan" },
      { matchType: "group", winner: "Messiah Hallberg & Sara Wimmercranz" },
      {
        matchType: "semifinal",
        semifinalFirst: "Ebba Kleberg von Sydow & Anders Tegnell",
        semifinalSecond: "Jennifer Kücükaslan & Johan Kücükaslan",
      },
      { matchType: "final", winner: "Ebba Kleberg von Sydow & Anders Tegnell" },
    ],
  },
  {
    name: "Oskar",
    bets: [
      { matchType: "group", winner: "Hector Apelgren & Peter Apelgren" },
      { matchType: "group", winner: "Hanna Dorsin & Emma Molin" },
      { matchType: "group", winner: "Hanna Dorsin & Emma Molin" },
      { matchType: "group", winner: "Ebba Kleberg von Sydow & Anders Tegnell" },
      { matchType: "group", winner: "Hanna Dorsin & Emma Molin" },
      { matchType: "group", winner: "Hector Apelgren & Peter Apelgren" },
      { matchType: "group", winner: "Farah Abadi & Johan Glans" },
      { matchType: "group", winner: "Farah Abadi & Johan Glans" },
      { matchType: "group", winner: "Jennifer Kücükaslan & Johan Kücükaslan" },
      { matchType: "group", winner: "Messiah Hallberg & Sara Wimmercranz" },
      { matchType: "group", winner: "Anders Eldeman & Christoffer Nyqvist" },
      { matchType: "group", winner: "Farah Abadi & Johan Glans" },
      {
        matchType: "semifinal",
        semifinalFirst: "Hector Apelgren & Peter Apelgren",
        semifinalSecond: "Hanna Dorsin & Emma Molin",
      },
      { matchType: "final", winner: "Hector Apelgren & Peter Apelgren" },
    ],
  },
  {
    name: "Selma",
    bets: [
      { matchType: "group", winner: "Hector Apelgren & Peter Apelgren" },
      { matchType: "group", winner: "Hanna Dorsin & Emma Molin" },
      { matchType: "group", winner: "Hanna Dorsin & Emma Molin" },
      { matchType: "group", winner: "Ebba Kleberg von Sydow & Anders Tegnell" },
      { matchType: "group", winner: "Hector Apelgren & Peter Apelgren" },
      { matchType: "group", winner: "Hector Apelgren & Peter Apelgren" },
      { matchType: "group", winner: "Farah Abadi & Johan Glans" },
      { matchType: "group", winner: "Jennifer Kücükaslan & Johan Kücükaslan" },
      { matchType: "group", winner: "Jennifer Kücükaslan & Johan Kücükaslan" },
      { matchType: "group", winner: "Messiah Hallberg & Sara Wimmercranz" },
      { matchType: "group", winner: "Jennifer Kücükaslan & Johan Kücükaslan" },
      { matchType: "group", winner: "Farah Abadi & Johan Glans" },
      {
        matchType: "semifinal",
        semifinalFirst: "Hector Apelgren & Peter Apelgren",
        semifinalSecond: "Farah Abadi & Johan Glans",
      },
      { matchType: "final", winner: "Farah Abadi & Johan Glans" },
    ],
  },
  {
    name: "Valle",
    bets: [
      { matchType: "group", winner: "Ebba Kleberg von Sydow & Anders Tegnell" },
      { matchType: "group", winner: "Hanna Dorsin & Emma Molin" },
      { matchType: "group", winner: "Gry Forssell & Jonas Rhodiner" },
      { matchType: "group", winner: "Ebba Kleberg von Sydow & Anders Tegnell" },
      { matchType: "group", winner: "Hector Apelgren & Peter Apelgren" },
      { matchType: "group", winner: "Hector Apelgren & Peter Apelgren" },
      { matchType: "group", winner: "Farah Abadi & Johan Glans" },
      { matchType: "group", winner: "Jennifer Kücükaslan & Johan Kücükaslan" },
      { matchType: "group", winner: "Jennifer Kücükaslan & Johan Kücükaslan" },
      { matchType: "group", winner: "Anders Eldeman & Christoffer Nyqvist" },
      { matchType: "group", winner: "Anders Eldeman & Christoffer Nyqvist" },
      { matchType: "group", winner: "Farah Abadi & Johan Glans" },
      {
        matchType: "semifinal",
        semifinalFirst: "Hector Apelgren & Peter Apelgren",
        semifinalSecond: "Anders Eldeman & Christoffer Nyqvist",
      },
      { matchType: "final", winner: "Hector Apelgren & Peter Apelgren" },
    ],
  },
];
